# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class BagExtractionConfiguration(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        BagExtractionConfiguration - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'description': 'str',
            'type': 'str',
            'config': 'object'
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'config': 'config'
        }

        self._name = None
        self._description = None
        self._type = None
        self._config = None

    @property
    def name(self):
        """
        Gets the name of this BagExtractionConfiguration.
        Name of the configuration

        :return: The name of this BagExtractionConfiguration.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this BagExtractionConfiguration.
        Name of the configuration

        :param name: The name of this BagExtractionConfiguration.
        :type: str
        """
        self._name = name

    @property
    def description(self):
        """
        Gets the description of this BagExtractionConfiguration.
        Description of this configuration

        :return: The description of this BagExtractionConfiguration.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this BagExtractionConfiguration.
        Description of this configuration

        :param description: The description of this BagExtractionConfiguration.
        :type: str
        """
        self._description = description

    @property
    def type(self):
        """
        Gets the type of this BagExtractionConfiguration.
        Type of the configuration. (only git is supported now)

        :return: The type of this BagExtractionConfiguration.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this BagExtractionConfiguration.
        Type of the configuration. (only git is supported now)

        :param type: The type of this BagExtractionConfiguration.
        :type: str
        """
        self._type = type

    @property
    def config(self):
        """
        Gets the config of this BagExtractionConfiguration.
        Data that is specific to the configuration type.

        :return: The config of this BagExtractionConfiguration.
        :rtype: object
        """
        return self._config

    @config.setter
    def config(self, config):
        """
        Sets the config of this BagExtractionConfiguration.
        Data that is specific to the configuration type.

        :param config: The config of this BagExtractionConfiguration.
        :type: object
        """
        self._config = config

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

