# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rbb_swagger_server.models.base_model_ import Model
from rbb_swagger_server import util


class BagStoreSummary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, detail_type: str=None, name: str=None):  # noqa: E501
        """BagStoreSummary - a model defined in Swagger

        :param detail_type: The detail_type of this BagStoreSummary.  # noqa: E501
        :type detail_type: str
        :param name: The name of this BagStoreSummary.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'detail_type': str,
            'name': str
        }

        self.attribute_map = {
            'detail_type': 'detail_type',
            'name': 'name'
        }

        self._detail_type = detail_type
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'BagStoreSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BagStoreSummary of this BagStoreSummary.  # noqa: E501
        :rtype: BagStoreSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail_type(self) -> str:
        """Gets the detail_type of this BagStoreSummary.


        :return: The detail_type of this BagStoreSummary.
        :rtype: str
        """
        return self._detail_type

    @detail_type.setter
    def detail_type(self, detail_type: str):
        """Sets the detail_type of this BagStoreSummary.


        :param detail_type: The detail_type of this BagStoreSummary.
        :type detail_type: str
        """
        if detail_type is None:
            raise ValueError("Invalid value for `detail_type`, must not be `None`")  # noqa: E501

        self._detail_type = detail_type

    @property
    def name(self) -> str:
        """Gets the name of this BagStoreSummary.


        :return: The name of this BagStoreSummary.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BagStoreSummary.


        :param name: The name of this BagStoreSummary.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
