# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rbb_swagger_server.models.base_model_ import Model
from rbb_swagger_server.models.bag_store_summary import BagStoreSummary  # noqa: F401,E501
from rbb_swagger_server import util


class BagStoreDetailed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, detail_type: str=None, name: str=None, description: str=None, store_type: str=None, store_data: object=None, created: datetime=None, default_file_store: str=None):  # noqa: E501
        """BagStoreDetailed - a model defined in Swagger

        :param detail_type: The detail_type of this BagStoreDetailed.  # noqa: E501
        :type detail_type: str
        :param name: The name of this BagStoreDetailed.  # noqa: E501
        :type name: str
        :param description: The description of this BagStoreDetailed.  # noqa: E501
        :type description: str
        :param store_type: The store_type of this BagStoreDetailed.  # noqa: E501
        :type store_type: str
        :param store_data: The store_data of this BagStoreDetailed.  # noqa: E501
        :type store_data: object
        :param created: The created of this BagStoreDetailed.  # noqa: E501
        :type created: datetime
        :param default_file_store: The default_file_store of this BagStoreDetailed.  # noqa: E501
        :type default_file_store: str
        """
        self.swagger_types = {
            'detail_type': str,
            'name': str,
            'description': str,
            'store_type': str,
            'store_data': object,
            'created': datetime,
            'default_file_store': str
        }

        self.attribute_map = {
            'detail_type': 'detail_type',
            'name': 'name',
            'description': 'description',
            'store_type': 'store_type',
            'store_data': 'store_data',
            'created': 'created',
            'default_file_store': 'default_file_store'
        }

        self._detail_type = detail_type
        self._name = name
        self._description = description
        self._store_type = store_type
        self._store_data = store_data
        self._created = created
        self._default_file_store = default_file_store

    @classmethod
    def from_dict(cls, dikt) -> 'BagStoreDetailed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BagStoreDetailed of this BagStoreDetailed.  # noqa: E501
        :rtype: BagStoreDetailed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail_type(self) -> str:
        """Gets the detail_type of this BagStoreDetailed.


        :return: The detail_type of this BagStoreDetailed.
        :rtype: str
        """
        return self._detail_type

    @detail_type.setter
    def detail_type(self, detail_type: str):
        """Sets the detail_type of this BagStoreDetailed.


        :param detail_type: The detail_type of this BagStoreDetailed.
        :type detail_type: str
        """
        if detail_type is None:
            raise ValueError("Invalid value for `detail_type`, must not be `None`")  # noqa: E501

        self._detail_type = detail_type

    @property
    def name(self) -> str:
        """Gets the name of this BagStoreDetailed.


        :return: The name of this BagStoreDetailed.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BagStoreDetailed.


        :param name: The name of this BagStoreDetailed.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this BagStoreDetailed.

        More information about this store.  # noqa: E501

        :return: The description of this BagStoreDetailed.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BagStoreDetailed.

        More information about this store.  # noqa: E501

        :param description: The description of this BagStoreDetailed.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def store_type(self) -> str:
        """Gets the store_type of this BagStoreDetailed.

        Type of store.  # noqa: E501

        :return: The store_type of this BagStoreDetailed.
        :rtype: str
        """
        return self._store_type

    @store_type.setter
    def store_type(self, store_type: str):
        """Sets the store_type of this BagStoreDetailed.

        Type of store.  # noqa: E501

        :param store_type: The store_type of this BagStoreDetailed.
        :type store_type: str
        """
        if store_type is None:
            raise ValueError("Invalid value for `store_type`, must not be `None`")  # noqa: E501

        self._store_type = store_type

    @property
    def store_data(self) -> object:
        """Gets the store_data of this BagStoreDetailed.

        Data that is specific to the store type.  # noqa: E501

        :return: The store_data of this BagStoreDetailed.
        :rtype: object
        """
        return self._store_data

    @store_data.setter
    def store_data(self, store_data: object):
        """Sets the store_data of this BagStoreDetailed.

        Data that is specific to the store type.  # noqa: E501

        :param store_data: The store_data of this BagStoreDetailed.
        :type store_data: object
        """
        if store_data is None:
            raise ValueError("Invalid value for `store_data`, must not be `None`")  # noqa: E501

        self._store_data = store_data

    @property
    def created(self) -> datetime:
        """Gets the created of this BagStoreDetailed.

        Date and time this store was added to the bazaar.  # noqa: E501

        :return: The created of this BagStoreDetailed.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created: datetime):
        """Sets the created of this BagStoreDetailed.

        Date and time this store was added to the bazaar.  # noqa: E501

        :param created: The created of this BagStoreDetailed.
        :type created: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def default_file_store(self) -> str:
        """Gets the default_file_store of this BagStoreDetailed.

        Name of the default file store (empty if no default store)  # noqa: E501

        :return: The default_file_store of this BagStoreDetailed.
        :rtype: str
        """
        return self._default_file_store

    @default_file_store.setter
    def default_file_store(self, default_file_store: str):
        """Sets the default_file_store of this BagStoreDetailed.

        Name of the default file store (empty if no default store)  # noqa: E501

        :param default_file_store: The default_file_store of this BagStoreDetailed.
        :type default_file_store: str
        """
        if default_file_store is None:
            raise ValueError("Invalid value for `default_file_store`, must not be `None`")  # noqa: E501

        self._default_file_store = default_file_store
