# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rbb_swagger_server.models.base_model_ import Model
from rbb_swagger_server.models.tag import Tag  # noqa: F401,E501
from rbb_swagger_server import util


class BagSummary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, detail_type: str=None, name: str=None, store_data: object=None, discovered: datetime=None, extraction_failure: bool=None, in_trash: bool=None, is_extracted: bool=None, meta_available: bool=None, size: int=None, start_time: datetime=None, end_time: datetime=None, data_start_time: datetime=None, data_end_time: datetime=None, duration: float=None, data_duration: float=None, messages: int=None, tags: List[Tag]=None):  # noqa: E501
        """BagSummary - a model defined in Swagger

        :param detail_type: The detail_type of this BagSummary.  # noqa: E501
        :type detail_type: str
        :param name: The name of this BagSummary.  # noqa: E501
        :type name: str
        :param store_data: The store_data of this BagSummary.  # noqa: E501
        :type store_data: object
        :param discovered: The discovered of this BagSummary.  # noqa: E501
        :type discovered: datetime
        :param extraction_failure: The extraction_failure of this BagSummary.  # noqa: E501
        :type extraction_failure: bool
        :param in_trash: The in_trash of this BagSummary.  # noqa: E501
        :type in_trash: bool
        :param is_extracted: The is_extracted of this BagSummary.  # noqa: E501
        :type is_extracted: bool
        :param meta_available: The meta_available of this BagSummary.  # noqa: E501
        :type meta_available: bool
        :param size: The size of this BagSummary.  # noqa: E501
        :type size: int
        :param start_time: The start_time of this BagSummary.  # noqa: E501
        :type start_time: datetime
        :param end_time: The end_time of this BagSummary.  # noqa: E501
        :type end_time: datetime
        :param data_start_time: The data_start_time of this BagSummary.  # noqa: E501
        :type data_start_time: datetime
        :param data_end_time: The data_end_time of this BagSummary.  # noqa: E501
        :type data_end_time: datetime
        :param duration: The duration of this BagSummary.  # noqa: E501
        :type duration: float
        :param data_duration: The data_duration of this BagSummary.  # noqa: E501
        :type data_duration: float
        :param messages: The messages of this BagSummary.  # noqa: E501
        :type messages: int
        :param tags: The tags of this BagSummary.  # noqa: E501
        :type tags: List[Tag]
        """
        self.swagger_types = {
            'detail_type': str,
            'name': str,
            'store_data': object,
            'discovered': datetime,
            'extraction_failure': bool,
            'in_trash': bool,
            'is_extracted': bool,
            'meta_available': bool,
            'size': int,
            'start_time': datetime,
            'end_time': datetime,
            'data_start_time': datetime,
            'data_end_time': datetime,
            'duration': float,
            'data_duration': float,
            'messages': int,
            'tags': List[Tag]
        }

        self.attribute_map = {
            'detail_type': 'detail_type',
            'name': 'name',
            'store_data': 'store_data',
            'discovered': 'discovered',
            'extraction_failure': 'extraction_failure',
            'in_trash': 'in_trash',
            'is_extracted': 'is_extracted',
            'meta_available': 'meta_available',
            'size': 'size',
            'start_time': 'start_time',
            'end_time': 'end_time',
            'data_start_time': 'data_start_time',
            'data_end_time': 'data_end_time',
            'duration': 'duration',
            'data_duration': 'data_duration',
            'messages': 'messages',
            'tags': 'tags'
        }

        self._detail_type = detail_type
        self._name = name
        self._store_data = store_data
        self._discovered = discovered
        self._extraction_failure = extraction_failure
        self._in_trash = in_trash
        self._is_extracted = is_extracted
        self._meta_available = meta_available
        self._size = size
        self._start_time = start_time
        self._end_time = end_time
        self._data_start_time = data_start_time
        self._data_end_time = data_end_time
        self._duration = duration
        self._data_duration = data_duration
        self._messages = messages
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'BagSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BagSummary of this BagSummary.  # noqa: E501
        :rtype: BagSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail_type(self) -> str:
        """Gets the detail_type of this BagSummary.


        :return: The detail_type of this BagSummary.
        :rtype: str
        """
        return self._detail_type

    @detail_type.setter
    def detail_type(self, detail_type: str):
        """Sets the detail_type of this BagSummary.


        :param detail_type: The detail_type of this BagSummary.
        :type detail_type: str
        """
        if detail_type is None:
            raise ValueError("Invalid value for `detail_type`, must not be `None`")  # noqa: E501

        self._detail_type = detail_type

    @property
    def name(self) -> str:
        """Gets the name of this BagSummary.


        :return: The name of this BagSummary.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BagSummary.


        :param name: The name of this BagSummary.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def store_data(self) -> object:
        """Gets the store_data of this BagSummary.

        Data that is specific to the bag store type.  # noqa: E501

        :return: The store_data of this BagSummary.
        :rtype: object
        """
        return self._store_data

    @store_data.setter
    def store_data(self, store_data: object):
        """Sets the store_data of this BagSummary.

        Data that is specific to the bag store type.  # noqa: E501

        :param store_data: The store_data of this BagSummary.
        :type store_data: object
        """
        if store_data is None:
            raise ValueError("Invalid value for `store_data`, must not be `None`")  # noqa: E501

        self._store_data = store_data

    @property
    def discovered(self) -> datetime:
        """Gets the discovered of this BagSummary.

        Date and time this bag was discovered.  # noqa: E501

        :return: The discovered of this BagSummary.
        :rtype: datetime
        """
        return self._discovered

    @discovered.setter
    def discovered(self, discovered: datetime):
        """Sets the discovered of this BagSummary.

        Date and time this bag was discovered.  # noqa: E501

        :param discovered: The discovered of this BagSummary.
        :type discovered: datetime
        """
        if discovered is None:
            raise ValueError("Invalid value for `discovered`, must not be `None`")  # noqa: E501

        self._discovered = discovered

    @property
    def extraction_failure(self) -> bool:
        """Gets the extraction_failure of this BagSummary.

        True if the extraction failed  # noqa: E501

        :return: The extraction_failure of this BagSummary.
        :rtype: bool
        """
        return self._extraction_failure

    @extraction_failure.setter
    def extraction_failure(self, extraction_failure: bool):
        """Sets the extraction_failure of this BagSummary.

        True if the extraction failed  # noqa: E501

        :param extraction_failure: The extraction_failure of this BagSummary.
        :type extraction_failure: bool
        """

        self._extraction_failure = extraction_failure

    @property
    def in_trash(self) -> bool:
        """Gets the in_trash of this BagSummary.

        True if the bag is in the trash bin.  # noqa: E501

        :return: The in_trash of this BagSummary.
        :rtype: bool
        """
        return self._in_trash

    @in_trash.setter
    def in_trash(self, in_trash: bool):
        """Sets the in_trash of this BagSummary.

        True if the bag is in the trash bin.  # noqa: E501

        :param in_trash: The in_trash of this BagSummary.
        :type in_trash: bool
        """

        self._in_trash = in_trash

    @property
    def is_extracted(self) -> bool:
        """Gets the is_extracted of this BagSummary.

        True if data is extracted from this bag.  # noqa: E501

        :return: The is_extracted of this BagSummary.
        :rtype: bool
        """
        return self._is_extracted

    @is_extracted.setter
    def is_extracted(self, is_extracted: bool):
        """Sets the is_extracted of this BagSummary.

        True if data is extracted from this bag.  # noqa: E501

        :param is_extracted: The is_extracted of this BagSummary.
        :type is_extracted: bool
        """
        if is_extracted is None:
            raise ValueError("Invalid value for `is_extracted`, must not be `None`")  # noqa: E501

        self._is_extracted = is_extracted

    @property
    def meta_available(self) -> bool:
        """Gets the meta_available of this BagSummary.

        True if meta data is known for this bag.  # noqa: E501

        :return: The meta_available of this BagSummary.
        :rtype: bool
        """
        return self._meta_available

    @meta_available.setter
    def meta_available(self, meta_available: bool):
        """Sets the meta_available of this BagSummary.

        True if meta data is known for this bag.  # noqa: E501

        :param meta_available: The meta_available of this BagSummary.
        :type meta_available: bool
        """
        if meta_available is None:
            raise ValueError("Invalid value for `meta_available`, must not be `None`")  # noqa: E501

        self._meta_available = meta_available

    @property
    def size(self) -> int:
        """Gets the size of this BagSummary.

        Size of the bag in bytes.  # noqa: E501

        :return: The size of this BagSummary.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this BagSummary.

        Size of the bag in bytes.  # noqa: E501

        :param size: The size of this BagSummary.
        :type size: int
        """

        self._size = size

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this BagSummary.

        Start time of this bag.  # noqa: E501

        :return: The start_time of this BagSummary.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this BagSummary.

        Start time of this bag.  # noqa: E501

        :param start_time: The start_time of this BagSummary.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self) -> datetime:
        """Gets the end_time of this BagSummary.

        End time of this bag.  # noqa: E501

        :return: The end_time of this BagSummary.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: datetime):
        """Sets the end_time of this BagSummary.

        End time of this bag.  # noqa: E501

        :param end_time: The end_time of this BagSummary.
        :type end_time: datetime
        """

        self._end_time = end_time

    @property
    def data_start_time(self) -> datetime:
        """Gets the data_start_time of this BagSummary.

        Start time of useful data in this bag.  # noqa: E501

        :return: The data_start_time of this BagSummary.
        :rtype: datetime
        """
        return self._data_start_time

    @data_start_time.setter
    def data_start_time(self, data_start_time: datetime):
        """Sets the data_start_time of this BagSummary.

        Start time of useful data in this bag.  # noqa: E501

        :param data_start_time: The data_start_time of this BagSummary.
        :type data_start_time: datetime
        """

        self._data_start_time = data_start_time

    @property
    def data_end_time(self) -> datetime:
        """Gets the data_end_time of this BagSummary.

        End time of useful data in this bag.  # noqa: E501

        :return: The data_end_time of this BagSummary.
        :rtype: datetime
        """
        return self._data_end_time

    @data_end_time.setter
    def data_end_time(self, data_end_time: datetime):
        """Sets the data_end_time of this BagSummary.

        End time of useful data in this bag.  # noqa: E501

        :param data_end_time: The data_end_time of this BagSummary.
        :type data_end_time: datetime
        """

        self._data_end_time = data_end_time

    @property
    def duration(self) -> float:
        """Gets the duration of this BagSummary.

        Duration of this bag in seconds.  # noqa: E501

        :return: The duration of this BagSummary.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration: float):
        """Sets the duration of this BagSummary.

        Duration of this bag in seconds.  # noqa: E501

        :param duration: The duration of this BagSummary.
        :type duration: float
        """

        self._duration = duration

    @property
    def data_duration(self) -> float:
        """Gets the data_duration of this BagSummary.

        Duration of useful data in this bag in seconds.  # noqa: E501

        :return: The data_duration of this BagSummary.
        :rtype: float
        """
        return self._data_duration

    @data_duration.setter
    def data_duration(self, data_duration: float):
        """Sets the data_duration of this BagSummary.

        Duration of useful data in this bag in seconds.  # noqa: E501

        :param data_duration: The data_duration of this BagSummary.
        :type data_duration: float
        """

        self._data_duration = data_duration

    @property
    def messages(self) -> int:
        """Gets the messages of this BagSummary.

        Number of messages in this bag.  # noqa: E501

        :return: The messages of this BagSummary.
        :rtype: int
        """
        return self._messages

    @messages.setter
    def messages(self, messages: int):
        """Sets the messages of this BagSummary.

        Number of messages in this bag.  # noqa: E501

        :param messages: The messages of this BagSummary.
        :type messages: int
        """

        self._messages = messages

    @property
    def tags(self) -> List[Tag]:
        """Gets the tags of this BagSummary.


        :return: The tags of this BagSummary.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[Tag]):
        """Sets the tags of this BagSummary.


        :param tags: The tags of this BagSummary.
        :type tags: List[Tag]
        """

        self._tags = tags
