# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rbb_swagger_server.models.base_model_ import Model
from rbb_swagger_server.models.bag_summary import BagSummary  # noqa: F401,E501
from rbb_swagger_server.models.simulation_run_summary import SimulationRunSummary  # noqa: F401,E501
from rbb_swagger_server import util


class SimulationRunDetailed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, detail_type: str=None, identifier: int=None, success: bool=None, description: str=None, duration: float=None, bag_name: str=None, bag_store_name: str=None, results: object=None, bag: BagSummary=None):  # noqa: E501
        """SimulationRunDetailed - a model defined in Swagger

        :param detail_type: The detail_type of this SimulationRunDetailed.  # noqa: E501
        :type detail_type: str
        :param identifier: The identifier of this SimulationRunDetailed.  # noqa: E501
        :type identifier: int
        :param success: The success of this SimulationRunDetailed.  # noqa: E501
        :type success: bool
        :param description: The description of this SimulationRunDetailed.  # noqa: E501
        :type description: str
        :param duration: The duration of this SimulationRunDetailed.  # noqa: E501
        :type duration: float
        :param bag_name: The bag_name of this SimulationRunDetailed.  # noqa: E501
        :type bag_name: str
        :param bag_store_name: The bag_store_name of this SimulationRunDetailed.  # noqa: E501
        :type bag_store_name: str
        :param results: The results of this SimulationRunDetailed.  # noqa: E501
        :type results: object
        :param bag: The bag of this SimulationRunDetailed.  # noqa: E501
        :type bag: BagSummary
        """
        self.swagger_types = {
            'detail_type': str,
            'identifier': int,
            'success': bool,
            'description': str,
            'duration': float,
            'bag_name': str,
            'bag_store_name': str,
            'results': object,
            'bag': BagSummary
        }

        self.attribute_map = {
            'detail_type': 'detail_type',
            'identifier': 'identifier',
            'success': 'success',
            'description': 'description',
            'duration': 'duration',
            'bag_name': 'bag_name',
            'bag_store_name': 'bag_store_name',
            'results': 'results',
            'bag': 'bag'
        }

        self._detail_type = detail_type
        self._identifier = identifier
        self._success = success
        self._description = description
        self._duration = duration
        self._bag_name = bag_name
        self._bag_store_name = bag_store_name
        self._results = results
        self._bag = bag

    @classmethod
    def from_dict(cls, dikt) -> 'SimulationRunDetailed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimulationRunDetailed of this SimulationRunDetailed.  # noqa: E501
        :rtype: SimulationRunDetailed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail_type(self) -> str:
        """Gets the detail_type of this SimulationRunDetailed.


        :return: The detail_type of this SimulationRunDetailed.
        :rtype: str
        """
        return self._detail_type

    @detail_type.setter
    def detail_type(self, detail_type: str):
        """Sets the detail_type of this SimulationRunDetailed.


        :param detail_type: The detail_type of this SimulationRunDetailed.
        :type detail_type: str
        """
        if detail_type is None:
            raise ValueError("Invalid value for `detail_type`, must not be `None`")  # noqa: E501

        self._detail_type = detail_type

    @property
    def identifier(self) -> int:
        """Gets the identifier of this SimulationRunDetailed.


        :return: The identifier of this SimulationRunDetailed.
        :rtype: int
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier: int):
        """Sets the identifier of this SimulationRunDetailed.


        :param identifier: The identifier of this SimulationRunDetailed.
        :type identifier: int
        """
        if identifier is None:
            raise ValueError("Invalid value for `identifier`, must not be `None`")  # noqa: E501

        self._identifier = identifier

    @property
    def success(self) -> bool:
        """Gets the success of this SimulationRunDetailed.


        :return: The success of this SimulationRunDetailed.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this SimulationRunDetailed.


        :param success: The success of this SimulationRunDetailed.
        :type success: bool
        """
        if success is None:
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success

    @property
    def description(self) -> str:
        """Gets the description of this SimulationRunDetailed.


        :return: The description of this SimulationRunDetailed.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this SimulationRunDetailed.


        :param description: The description of this SimulationRunDetailed.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def duration(self) -> float:
        """Gets the duration of this SimulationRunDetailed.


        :return: The duration of this SimulationRunDetailed.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration: float):
        """Sets the duration of this SimulationRunDetailed.


        :param duration: The duration of this SimulationRunDetailed.
        :type duration: float
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")  # noqa: E501

        self._duration = duration

    @property
    def bag_name(self) -> str:
        """Gets the bag_name of this SimulationRunDetailed.


        :return: The bag_name of this SimulationRunDetailed.
        :rtype: str
        """
        return self._bag_name

    @bag_name.setter
    def bag_name(self, bag_name: str):
        """Sets the bag_name of this SimulationRunDetailed.


        :param bag_name: The bag_name of this SimulationRunDetailed.
        :type bag_name: str
        """

        self._bag_name = bag_name

    @property
    def bag_store_name(self) -> str:
        """Gets the bag_store_name of this SimulationRunDetailed.


        :return: The bag_store_name of this SimulationRunDetailed.
        :rtype: str
        """
        return self._bag_store_name

    @bag_store_name.setter
    def bag_store_name(self, bag_store_name: str):
        """Sets the bag_store_name of this SimulationRunDetailed.


        :param bag_store_name: The bag_store_name of this SimulationRunDetailed.
        :type bag_store_name: str
        """

        self._bag_store_name = bag_store_name

    @property
    def results(self) -> object:
        """Gets the results of this SimulationRunDetailed.

        Configuration of the simulation.  # noqa: E501

        :return: The results of this SimulationRunDetailed.
        :rtype: object
        """
        return self._results

    @results.setter
    def results(self, results: object):
        """Sets the results of this SimulationRunDetailed.

        Configuration of the simulation.  # noqa: E501

        :param results: The results of this SimulationRunDetailed.
        :type results: object
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results

    @property
    def bag(self) -> BagSummary:
        """Gets the bag of this SimulationRunDetailed.

        Read only value, expanded on request.  # noqa: E501

        :return: The bag of this SimulationRunDetailed.
        :rtype: BagSummary
        """
        return self._bag

    @bag.setter
    def bag(self, bag: BagSummary):
        """Sets the bag of this SimulationRunDetailed.

        Read only value, expanded on request.  # noqa: E501

        :param bag: The bag of this SimulationRunDetailed.
        :type bag: BagSummary
        """

        self._bag = bag
